language: python
env:
    - PYTHON_VER=2.6
    - PYTHON_VER=2.7
    - PYTHON_VER=3.2
    - PYTHON_VER=3.3
    - PYTHON_VER=3.4

sudo: false
cache:
  directories:
  - python$PYTHON_VER

notifications:
  email:
    - buildout-development@googlegroups.com

install:
    - deactivate
    - make build

script: make test
