language: python
dist: xenial

matrix:
    include:
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.4"
          env: TOXENV=py34
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36

cache:
  pip: true

notifications:
  email:
    - buildout-development@googlegroups.com

install:
    - travis_retry pip install -U tox

script:
    - export COVERAGE_PROCESS_START=
    - travis_retry tox
