language: python
env:
    - PYTHON_VER=2.6
    - PYTHON_VER=2.7
    - PYTHON_VER=3.2
    - PYTHON_VER=3.3
    - PYTHON_VER=3.4

sudo: false
cache:
  directories:
  - pythons
# Note on these cache directories: "make build" downloads and installs a fresh
# python in those directories.

notifications:
  email:
    - buildout-development@googlegroups.com

install:
    - ls -al python*
    - ls -al python*/bin/
    - deactivate
    - make build

script: make test
